# Generated by Django 4.2.5 on 2023-09-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='is_available',
        ),
    ]
