# Generated by Django 4.2.5 on 2023-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'В обработке'), ('WT', 'Ожидание'), ('CM', 'Выполнен')], default='PR', max_length=2),
        ),
    ]
